CREATE TABLE [dbo].[QA_tbl_Lookup_Measure] (
    [Measure_ID]             INT             IDENTITY (1, 1) NOT NULL,
    [Measure_num]            VARCHAR (50)    NOT NULL,
    [Measure_Title]          VARCHAR (500)   NOT NULL,
    [Measure_Desc]           VARCHAR (1000)  NOT NULL,
    [PQRS_Flag]              BIT             NULL,
    [Age_Restriction_From]   DECIMAL (18, 2) NULL,
    [Denominator_Question]   VARCHAR (500)   NULL,
    [Denominator_Ques_Desc]  VARCHAR (5000)  NULL,
    [Numerator_Question]     VARCHAR (500)   NULL,
    [Numerator_Ques_Desc]    VARCHAR (5000)  NULL,
    [Possible_Exclusion]     BIT             NULL,
    [NQS_Domain_Code]        VARCHAR (50)    NULL,
    [Measure_type]           VARCHAR (50)    NULL,
    [Begin_Date]             DATE            NULL,
    [End_Date]               DATE            NULL,
    [Created_Date]           DATE            NULL,
    [Created_By]             VARCHAR (50)    NULL,
    [Last_Mod_Date]          DATE            NULL,
    [Last_Mod_By]            VARCHAR (50)    NULL,
    [Mandatory_Diagnos_Code] BIT             NULL,
    [ForCMSSubmission]       BIT             NULL,
    [PhysGroupMeasure]       BIT             NULL,
    [CMSYear]                INT             NOT NULL,
    [Allow_Portal_Submit]    BIT             NOT NULL,
    [Measure_Scoring]        VARCHAR (10)    NULL,
    [Measuere_Group]         BIT             NOT NULL,
    [Inverse_Measure]        BIT             NOT NULL,
    [CMS_Message]            VARCHAR (5000)  NULL,
    [DisplayOrder]           INT             NULL,
    [Perf_Rate_Per_1000]     BIT             NOT NULL,
    [Age_Restriction_To]     DECIMAL (18, 2) NULL,
    [Gender_Restriction]     VARCHAR (8)     NULL,
    [IsAcceptableDateRange]  BIT             NULL,
    [value_type]             NVARCHAR (50)   NULL,
    [value_unit]             NVARCHAR (50)   NULL,
    [score_type]             NVARCHAR (50)   NULL,
    [IsStratum_Required]     BIT             NULL,
    [Is_DiagCodeAsKey]       BIT             NULL,
    [Priority_ID]            INT             NULL,
    [Is_AvgMeasure]          BIT             NULL,
    [Is_eCQM]                BIT             NULL
);

