CREATE TABLE [dbo].[tbl_Data_Error] (
    [Id]                           INT            IDENTITY (1, 1) NOT NULL,
    [Exam_Date]                    VARCHAR (500)  NULL,
    [Exam_TIN]                     VARCHAR (500)  NULL,
    [Physician_NPI]                VARCHAR (500)  NULL,
    [Patient_ID]                   VARCHAR (500)  NULL,
    [Patient_Age]                  VARCHAR (500)  NULL,
    [Patient_Gender]               VARCHAR (500)  NULL,
    [Patient_Medicare_Beneficiary] VARCHAR (500)  NULL,
    [Patient_Medicare_Advantage]   VARCHAR (500)  NULL,
    [Measure_Num]                  VARCHAR (500)  NULL,
    [Denominator_Proc_code]        VARCHAR (500)  NULL,
    [Denominator_Diag_code]        VARCHAR (500)  NULL,
    [Numerator_Response_Value]     VARCHAR (500)  NULL,
    [Measure_Extension_Number]     VARCHAR (500)  NULL,
    [Extension_Response_value]     VARCHAR (500)  NULL,
    [Exam_Unique_ID]               VARCHAR (500)  NULL,
    [Error_Msg]                    VARCHAR (2000) NULL,
    [DataSource_Id]                INT            NULL,
    [CMS_Submission_Year]          INT            NULL,
    [File_ID]                      INT            NULL,
    [Transaction_ID]               VARCHAR (50)   NULL,
    [Created_Date]                 DATETIME       NULL,
    [Created_By]                   VARCHAR (50)   NULL,
    [Warning]                      VARCHAR (2000) NULL,
    [Exclusion]                    VARCHAR (2000) NULL,
    [FileRow_Num]                  INT            NULL,
    CONSTRAINT [PK_tbl_Data_Error] PRIMARY KEY CLUSTERED ([Id] ASC)
);

