CREATE TABLE [dbo].[tbl_CI_BulkFileUploadCmsData] (
    [CmsDataId]                INT           IDENTITY (1, 1) NOT NULL,
    [FileId]                   INT           NULL,
    [TIN]                      VARCHAR (9)   NULL,
    [Npi]                      VARCHAR (10)  NULL,
    [Measure_Name]             VARCHAR (50)  NULL,
    [CmsYear]                  INT           NULL,
    [NoofExamsSubmitted]       VARCHAR (50)  NULL,
    [Total_no_of_exams_old]    VARCHAR (50)  NULL,
    [Total_no_of_exams_new]    VARCHAR (50)  NULL,
    [HundredPercentSubmit_old] VARCHAR (50)  NULL,
    [HundredPercentSubmit_new] VARCHAR (50)  NULL,
    [SelectedForCms_old]       VARCHAR (50)  NULL,
    [SelectedForCms_new]       VARCHAR (50)  NULL,
    [Performac_Rate]           VARCHAR (50)  NULL,
    [Decile]                   VARCHAR (50)  NULL,
    [Reporting_Rate]           VARCHAR (50)  NULL,
    [Createdby]                VARCHAR (50)  NULL,
    [CreatedDate]              DATETIME      NULL,
    [Is_MeasureDataUpdated]    BIT           NULL,
    [Is_PerformanceCalculated] BIT           NULL,
    [IsRowEditedByUser]        BIT           NULL,
    [IsValidata]               BIT           NULL,
    [ErrorMessage]             VARCHAR (MAX) NULL,
    [EndtoEndReporting_old]    VARCHAR (10)  NULL,
    [EndtoEndReporting_new]    VARCHAR (10)  NULL,
    CONSTRAINT [PK__tbl_CI_B__C08907F80592D996] PRIMARY KEY CLUSTERED ([CmsDataId] ASC),
    CONSTRAINT [FK_tbl_CI_BulkFileUploadCmsData_tbl_CI_BulkFileUpload_History] FOREIGN KEY ([FileId]) REFERENCES [dbo].[tbl_CI_BulkFileUpload_History] ([FileId]) ON DELETE CASCADE
);

