CREATE TABLE [dbo].[tbl_Lookup_Decile_Data_dummy] (
    [Sno]                INT             NULL,
    [Measure_Name]       VARCHAR (600)   NULL,
    [Measure_num]        VARCHAR (50)    NULL,
    [Submission_Method]  VARCHAR (100)   NULL,
    [Measure_Type]       VARCHAR (50)    NULL,
    [Benchmark]          BIT             NULL,
    [Decile_3_from]      DECIMAL (18, 5) NULL,
    [Decile_3_to]        DECIMAL (18, 5) NULL,
    [Decile_4_from]      DECIMAL (18, 5) NULL,
    [Decile_4_to]        DECIMAL (18, 5) NULL,
    [Decile_5_from]      DECIMAL (18, 5) NULL,
    [Decile_5_to]        DECIMAL (18, 5) NULL,
    [Decile_6_from]      DECIMAL (18, 5) NULL,
    [Decile_6_to]        DECIMAL (18, 5) NULL,
    [Decile_7_from]      DECIMAL (18, 5) NULL,
    [Decile_7_to]        DECIMAL (18, 5) NULL,
    [Decile_8_from]      DECIMAL (18, 5) NULL,
    [Decile_8_to]        DECIMAL (18, 5) NULL,
    [Decile_9_from]      DECIMAL (18, 5) NULL,
    [Decile_9_to]        DECIMAL (18, 5) NULL,
    [Decile_10_from]     DECIMAL (18, 5) NULL,
    [Decile_10_to]       DECIMAL (18, 5) NULL,
    [Topped Out]         BIT             NULL,
    [Is_Low_to_High]     BIT             NULL,
    [CMSYear]            INT             NULL,
    [SevenPointCap]      BIT             NULL,
    [Standard_Deviation] DECIMAL (18, 5) NULL,
    [Average]            DECIMAL (18, 5) NULL
);

