CREATE TYPE [dbo].[tbl_CI_Submission_Score_Type] AS TABLE (
    [Response_Id]                      INT             NULL,
    [Response_Data]                    VARCHAR (MAX)   NOT NULL,
    [QM_Weight_Score]                  DECIMAL (18, 4) NULL,
    [QM_UnWeight_Score]                DECIMAL (18, 4) NULL,
    [QM_Max_Contribution]              DECIMAL (18, 4) NULL,
    [QM_Weight_Msg]                    VARCHAR (250)   NULL,
    [QM_hasACRMeasure]                 BIT             NULL,
    [QM_hasQualityMeasures]            BIT             NULL,
    [IA_Weight_Score]                  DECIMAL (18, 4) NULL,
    [IA_UnWeight_Score]                DECIMAL (18, 4) NULL,
    [IA_Max_Contribution]              DECIMAL (18, 4) NULL,
    [IA_Weight_Msg]                    VARCHAR (250)   NULL,
    [IA_hasIAWeightStatus]             VARCHAR (50)    NULL,
    [IA_givenIACreditPCMH]             BIT             NULL,
    [IA_givenIAStudyCredit]            BIT             NULL,
    [IA_feedback_message]              VARCHAR (MAX)   NULL,
    [PI_Weight_Score]                  DECIMAL (18, 4) NULL,
    [PI_Max_Contribution]              DECIMAL (18, 4) NULL,
    [PI_Weight_Msg]                    VARCHAR (250)   NULL,
    [PI_baseScore]                     DECIMAL (18, 4) NULL,
    [PI_attestationBonusEligible]      DECIMAL (18, 4) NULL,
    [PI_performance]                   DECIMAL (18, 4) NULL,
    [PI_bonus]                         DECIMAL (18, 4) NULL,
    [PI_cehrt_bonus]                   DECIMAL (18, 4) NULL,
    [PI_base_max]                      DECIMAL (18, 4) NULL,
    [PI_performance_max]               DECIMAL (18, 4) NULL,
    [PI_bonus_max]                     DECIMAL (18, 4) NULL,
    [PI_cehrt_bonus_max]               DECIMAL (18, 4) NULL,
    [PI_UnWeight_Score]                DECIMAL (18, 4) NULL,
    [PI_feedback_message]              VARCHAR (MAX)   NULL,
    [Total_Score]                      DECIMAL (18, 4) NULL,
    [CMS_Error_Message]                VARCHAR (MAX)   NULL,
    [CMS_Warning_Message]              VARCHAR (MAX)   NULL,
    [PI_hasMinimumPIPerformancePeriod] BIT             NULL);

