CREATE TYPE [dbo].[tbl_Exam_Type] AS TABLE (
    [Exam_Record_UniqueId]         UNIQUEIDENTIFIER NOT NULL,
    [Measure_num]                  VARCHAR (50)     NULL,
    [Examdate]                     VARCHAR (50)     NULL,
    [Exam_Unique_ID]               VARCHAR (500)    NULL,
    [Exam_TIN]                     VARCHAR (10)     NULL,
    [Physician_NPI]                VARCHAR (50)     NULL,
    [Patient_ID]                   VARCHAR (500)    NULL,
    [IsEncrypt]                    VARCHAR (10)     NULL,
    [Patient_Age]                  VARCHAR (10)     NULL,
    [Patient_Gender]               VARCHAR (50)     NULL,
    [Patient_Medicare_Beneficiary] VARCHAR (50)     NULL,
    [Patient_Medicare_Advantage]   VARCHAR (50)     NULL,
    [PartnerID]                    VARCHAR (50)     NULL,
    [Created_Date]                 VARCHAR (50)     NULL,
    [Created_By]                   VARCHAR (50)     NULL,
    [DataSource_Id]                VARCHAR (50)     NULL,
    [CMS_Submission_Year]          VARCHAR (50)     NULL,
    [File_ID]                      VARCHAR (50)     NULL,
    [DecryptPatient_Id]            VARCHAR (500)    NULL,
    [Procedure_Code]               VARCHAR (50)     NULL,
    [Last_Modified_Date]           VARCHAR (50)     NULL,
    [Last_Modified_By]             VARCHAR (50)     NULL,
    [Criteria]                     VARCHAR (20)     NULL,
    [warningFound]                 BIT              DEFAULT ((0)) NOT NULL,
    [addedRecordsWithWarning]      INT              DEFAULT ((0)) NULL,
    [addedRecords]                 INT              DEFAULT ((0)) NULL,
    [updatedRecordsWithWarning]    INT              DEFAULT ((0)) NOT NULL,
    [updatedRecords]               INT              DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([Exam_Record_UniqueId] ASC));

